; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.13 on Wed Sep 14 2022 22:04:10 GMT+0100 (British Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


