; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.13 on Wed Sep 14 2022 22:04:11 GMT+0100 (British Summer Time)

